### ISSUE TITLE
Escape key to quit diff views

### ISSUE THREAD

**Issue by Nikaoto** [CJTozer/SublimeDiffView#55] opened 2018-01-28 23:10 UTC
It would be very useful if it were possible to quit the diff views when viewing them.

For example, if I'm viewing my uncommited changes:
![diff-view](https://user-images.githubusercontent.com/21026339/35488366-ffaf8dfc-04a0-11e8-9cf9-e01a28867244.png)

Pressing `escape` would take me back to the state I was last in before activating the diff view:
![edit-view](https://user-images.githubusercontent.com/21026339/35488407-e23ced7c-04a1-11e8-906e-96dbb97ebb38.png)

**Comment by CJTozer** [comment] 2018-01-29 10:12
Thanks for the input - yes this is a duplicate of #22, which I'll aim to take another look at.

**Closed by CJTozer** 2018-01-29 10:12 UTC
